import {
    ef_production_machine,
    ef_synthesis_machine,
    ef_logistics_device,
    ef_storage_device,
    ef_power_device
} from './categories';
import type { ef_device } from './ef_device';

export const all_ef_devices: ef_device[] =
[
    new ef_production_machine('shaping_machine', '塑型機', 3, 3, 10, [{"id":"base_mode","label":"基礎模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null},{"id":"gas_mode","label":"氣體模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"left","offset":1,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('filling_machine', '灌裝機', 6, 4, 20, [{"id":"base_mode","label":"基礎模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"top","offset":5,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"},{"side":"bottom","offset":5,"media":"belt"}],"loss":null},{"id":"gas_liquid_mode","label":"氣液模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"top","offset":5,"media":"belt"},{"side":"left","offset":1,"media":"pipe"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"},{"side":"bottom","offset":5,"media":"belt"}],"loss":null}]),
    new ef_production_machine('refinery', '精煉爐', 3, 3, 5, [{"id":"base_mode","label":"基礎模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null},{"id":"liquid_mode","label":"液體模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"left","offset":1,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null}]),
    new ef_production_machine('crusher', '粉碎機', 3, 3, 5, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null}]),
    new ef_production_machine('parts_machine', '配件機', 3, 3, 20, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('equipment_parts_machine', '裝備原件機', 4, 6, 10, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"belt"},{"side":"left","offset":1,"media":"belt"},{"side":"left","offset":2,"media":"belt"},{"side":"left","offset":3,"media":"belt"},{"side":"left","offset":4,"media":"belt"},{"side":"left","offset":5,"media":"belt"}],"output_ports":[{"side":"right","offset":0,"media":"belt"},{"side":"right","offset":1,"media":"belt"},{"side":"right","offset":2,"media":"belt"},{"side":"right","offset":3,"media":"belt"},{"side":"right","offset":4,"media":"belt"},{"side":"right","offset":5,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('packaging_machine', '封裝機', 6, 4, 20, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"top","offset":5,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"},{"side":"bottom","offset":5,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('grinder', '研磨機', 6, 4, 50, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"top","offset":5,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"},{"side":"bottom","offset":5,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('reactor', '反應池', 5, 5, 50, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"left","offset":1,"media":"belt"},{"side":"left","offset":3,"media":"belt"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('tianyou_furnace', '天有洪爐', 5, 5, 50, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"left","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"}],"loss":null}]),
    new ef_synthesis_machine('purifier', '提純機', 5, 5, 50, [{"id":"liquid_mode","label":"液體模式","input_ports":[{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":null},{"id":"gas_mode","label":"氣體模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"left","offset":2,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":null}]),
    new ef_synthesis_machine('disassembler', '拆解機', 6, 4, 20, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"top","offset":5,"media":"belt"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"},{"side":"bottom","offset":5,"media":"belt"}],"loss":null}]),
    new ef_logistics_device('item_access_port', '物品准入口', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"belt"}],"output_ports":[{"side":"right","offset":0,"media":"belt"}],"loss":null}]),
    new ef_logistics_device('splitter', '分流器', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"belt"}],"output_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"right","offset":0,"media":"belt"},{"side":"bottom","offset":0,"media":"belt"}],"loss":null}]),
    new ef_logistics_device('logistics_bridge', '物流橋', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"belt"},{"side":"bottom","offset":0,"media":"belt"}],"output_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"right","offset":0,"media":"belt"}],"loss":null}]),
    new ef_logistics_device('merger', '匯流器', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"left","offset":0,"media":"belt"},{"side":"bottom","offset":0,"media":"belt"}],"output_ports":[{"side":"right","offset":0,"media":"belt"}],"loss":null}]),
    new ef_logistics_device('pipe_access_port', '管道准入口', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"pipe"}],"output_ports":[{"side":"right","offset":0,"media":"pipe"}],"loss":null}]),
    new ef_logistics_device('pipe_splitter', '管道分流器', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"pipe"}],"output_ports":[{"side":"top","offset":0,"media":"pipe"},{"side":"right","offset":0,"media":"pipe"},{"side":"bottom","offset":0,"media":"pipe"}],"loss":null}]),
    new ef_logistics_device('pipe_bridge', '管道橋', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":0,"media":"pipe"},{"side":"bottom","offset":0,"media":"pipe"}],"output_ports":[{"side":"top","offset":0,"media":"pipe"},{"side":"right","offset":0,"media":"pipe"}],"loss":null}]),
    new ef_logistics_device('pipe_merger', '管道匯流器', 1, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"pipe"},{"side":"left","offset":0,"media":"pipe"},{"side":"bottom","offset":0,"media":"pipe"}],"output_ports":[{"side":"right","offset":0,"media":"pipe"}],"loss":null}]),
    new ef_storage_device('protocol_storage_box', '協議儲存箱', 3, 3, 5, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"}],"loss":null}]),
    new ef_storage_device('warehouse_input', '倉庫存貨口', 3, 1, 0, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":1,"media":"belt"}],"output_ports":[],"loss":null}]),
    new ef_storage_device('warehouse_output', '倉庫取貨口', 3, 1, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[{"side":"top","offset":1,"media":"belt"}],"loss":null}]),
    new ef_storage_device('liquid_tank', '儲液罐', 3, 3, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"}],"loss":null}]),
    new ef_storage_device('warehouse_line_base', '倉庫存取線基段', 4, 8, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_storage_device('warehouse_line_source', '倉庫存取線源樁', 4, 4, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_storage_device('conduit_inlet', '暗管入口', 3, 3, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"}],"output_ports":[],"loss":null}]),
    new ef_storage_device('conduit_outlet', '暗管出口', 3, 3, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[{"side":"right","offset":1,"media":"pipe"}],"loss":null}]),
    new ef_storage_device('multi_conduit_inlet', '多口暗管入口', 3, 5, 0, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[],"loss":null}]),
    new ef_storage_device('multi_conduit_outlet', '多口暗管出口', 3, 5, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":null}]),
    new ef_production_machine('seed_harvester', '採種機', 5, 5, 10, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"}],"loss":null}]),
    new ef_production_machine('planter', '種植機', 5, 5, 20, [{"id":"base_mode","label":"基礎模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"}],"loss":null},{"id":"liquid_mode","label":"液體模式","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"left","offset":2,"media":"pipe"}],"output_ports":[{"side":"bottom","offset":0,"media":"belt"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"}],"loss":null}]),
    new ef_production_machine('wastewater_processor', '廢水處理機', 3, 3, 50, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"}],"output_ports":[],"loss":null}]),
    new ef_synthesis_machine('large_reactor', '擴容反應池', 6, 5, 100, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"belt"},{"side":"top","offset":3,"media":"belt"},{"side":"top","offset":4,"media":"belt"},{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"},{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":2,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"},{"side":"bottom","offset":4,"media":"belt"}],"loss":null}]),
    new ef_power_device('power_pole', '供電樁', 2, 2, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_power_device('xi_rang_power_pole', '息壤供電樁', 2, 2, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_power_device('relay', '中繼器', 3, 3, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_power_device('xi_rang_relay', '息壤中繼器', 3, 3, 0, [{"id":"default","label":"預設","input_ports":[],"output_ports":[],"loss":null}]),
    new ef_power_device('thermal_pool', '熱能池', 2, 2, 0, [{"id":"default","label":"預設","input_ports":[{"side":"top","offset":0,"media":"belt"},{"side":"top","offset":1,"media":"belt"}],"output_ports":[],"loss":null}]),
    new ef_synthesis_machine('liquid_gas_converter', '液氣轉化機', 5, 5, 50, [{"id":"liquid_mode","label":"液體產出","input_ports":[{"side":"top","offset":2,"media":"pipe"},{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":{"item":"液化息壤","rate_per_min":6}},{"id":"gas_mode","label":"氣體產出","input_ports":[{"side":"top","offset":2,"media":"pipe"},{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":{"item":"液化息壤","rate_per_min":6}}]),
    new ef_synthesis_machine('solid_gas_converter', '固氣轉化機', 5, 5, 50, [{"id":"solid_mode","label":"固體產出","input_ports":[{"side":"top","offset":2,"media":"pipe"},{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"bottom","offset":1,"media":"belt"},{"side":"bottom","offset":3,"media":"belt"}],"loss":{"item":"息壤氣","rate_per_min":6}},{"id":"gas_mode","label":"氣體產出","input_ports":[{"side":"top","offset":1,"media":"belt"},{"side":"top","offset":2,"media":"pipe"},{"side":"top","offset":3,"media":"belt"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":{"item":"息壤氣","rate_per_min":6}}]),
    new ef_synthesis_machine('gas_reactor', '氣體反應爐', 5, 5, 50, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"},{"side":"left","offset":3,"media":"pipe"}],"output_ports":[{"side":"right","offset":1,"media":"pipe"},{"side":"right","offset":3,"media":"pipe"}],"loss":null}]),
    new ef_synthesis_machine('gas_disperser', '氣體散布機', 3, 3, -1, [{"id":"default","label":"預設","input_ports":[{"side":"left","offset":1,"media":"pipe"}],"output_ports":[],"loss":null}]),
    new ef_storage_device('material_source', '基礎材料輸出點', 1, 3, 0, [{"id":"solid_belt","label":"固體輸送帶","input_ports":[],"output_ports":[{"side":"right","offset":1,"media":"belt"}],"loss":null},{"id":"fluid_pipe","label":"液氣管道","input_ports":[],"output_ports":[{"side":"right","offset":1,"media":"pipe"}],"loss":null}])
];

export const ef_device_map = new Map<string, ef_device>(all_ef_devices.map(d => [d.id, d]));
