#!/usr/bin/env python3
"""Regenerate `head.md` and check `docs/history/` for internal conflicts.

Stdlib only — no venv needed. Parsing and consistency rules live in
`plan_parse.py`, which every tool in this directory shares; this file is only the
`head.md` rendering and the CLI/hook around it.

    python docs/history/update-head.py          # manual run, report on stdout
    python docs/history/update-head.py --check  # check only, never write head.md
    python docs/history/update-head.py --hook   # PostToolUse hook (reads hook JSON on stdin)

`head.md` is a pure function of the plan files (no timestamp), so a no-op run
produces a byte-identical file and never shows up as a spurious diff.

Exit codes: 0 clean · 1 conflicts (manual) · 2 conflicts (--hook, so the agent is
shown stderr).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from plan_parse import (
    HERE,
    NON_PLAN_FILES,
    ROOT_DISPLAY,
    Conflict,
    Plan,
    LIVE_STATUSES,
    blockers,
    collect,
    display_state,
    force_utf8_stdio,
    format_conflicts,
    item_index,
)

HEAD = HERE / "head.md"

# HEAD is the highest-seq plan in the first non-empty bucket.
HEAD_PREFERENCE = ("in-progress", "draft", "done")


def pick_head(plans: list[Plan]) -> Plan | None:
    for status in HEAD_PREFERENCE:
        bucket = [p for p in plans if p.status == status]
        if bucket:
            return max(bucket, key=lambda p: p.seq)
    return None


def _link(p: Plan) -> str:
    return f"[{p.stem}](./{p.name})"


def _remaining(p: Plan) -> str:
    line = f"remaining tasks {p.open_items}/{p.total}"
    if p.handoff_count:
        line += f", handed off {p.handoff_count}"
    return line


def render_open_items(plans: list[Plan]) -> list[str]:
    """One line per open item, across every live plan."""
    index = item_index(plans)
    live = sorted((p for p in plans if p.status in LIVE_STATUSES), key=lambda p: p.seq, reverse=True)
    rows = [it for p in live for it in p.items if it.is_open]

    out = ["", "## Open Items (Itemized)", ""]
    if rows:
        for it in rows:
            line = f"- `{it.addr}` · **{display_state(it, index)}**"
            if held := blockers(it, index):
                line += " (waiting for " + ", ".join(f"`{a}`" for a in held) + ")"
            out.append(f"{line} — {it.title}")
        out += [
            "",
            f"> To work on a specific item: `python3 {ROOT_DISPLAY}/plan-item.py {rows[0].addr}`",
            "> —— returns only that item's body and basis, without needing to read the entire plan.",
        ]
    else:
        out.append("(No open items)")

    return out


def render_head(plans: list[Plan], conflicts: list[Conflict]) -> str:
    out = [
        "# Plan history — HEAD",
        "",
        f"<!-- Generated by {ROOT_DISPLAY}/update-head.py — do not hand-edit. -->",
        "",
        "## Current in Use",
        "",
    ]

    head = pick_head(plans)
    if head is None:
        out.append("(No plans yet)")
    else:
        line = f"{_link(head)} — `{head.status}`"
        if head.status == "in-progress":
            line += f", {_remaining(head)}"
        out.append(line)

    out += render_open_items(plans)
    out += ["", "## draft / in-progress (Descending by Seq)", ""]

    live = sorted(
        (p for p in plans if p.status in LIVE_STATUSES),
        key=lambda p: p.seq,
        reverse=True,
    )
    if not live:
        out.append("(None)")
    for p in live:
        line = f"- **{p.seq}** {_link(p)} — `{p.status}`"
        if p.status == "in-progress":
            line += f", {_remaining(p)}"
        out.append(line)

    if conflicts:
        out += [
            "",
            f"> ⚠ {len(conflicts)} consistency conflict(s) unresolved.",
            f"> Run `python3 {ROOT_DISPLAY}/update-head.py` to see details.",
        ]

    return "\n".join(out) + "\n"


def hook_should_run() -> bool:
    """True when the PostToolUse payload on stdin touched a plan file."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return False
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not raw:
        return False
    try:
        path = Path(raw).resolve()
    except OSError:
        return False
    return path.parent == HERE and path.name not in NON_PLAN_FILES and path.suffix == ".md"


def main() -> int:
    force_utf8_stdio()
    args = set(sys.argv[1:])
    hook = "--hook" in args
    check_only = "--check" in args

    if hook and not hook_should_run():
        return 0

    report = collect()

    if not check_only:
        rendered = render_head(report.plans, report.errors)
        if not HEAD.exists() or HEAD.read_text(encoding="utf-8") != rendered:
            HEAD.write_text(rendered, encoding="utf-8")
            if not hook:
                print(f"[plan-history] head.md updated ({len(report.plans)} plan(s))")
        elif not hook:
            print(f"[plan-history] head.md already up to date ({len(report.plans)} plan(s))")

    if not report.conflicts:
        return 0

    text = format_conflicts(report.conflicts)
    if hook:
        print(text, file=sys.stderr)
        return 2 if report.errors else 0
    print(text)
    return 1 if report.errors else 0


if __name__ == "__main__":
    sys.exit(main())
