#!/usr/bin/env python3
"""Regenerate `head.md` and check `docs/dernoson/plan-history/` for internal conflicts.

Stdlib only — no venv needed. Parsing and the consistency rules live in
`plan_parse.py`, which every tool in this directory shares; this file is only the
`head.md` rendering and the CLI/hook around it.

    python3 docs/dernoson/plan-history/update-head.py          # manual run, report on stdout
    python3 docs/dernoson/plan-history/update-head.py --check  # check only, never write head.md
    python3 docs/dernoson/plan-history/update-head.py --hook   # PostToolUse hook (reads hook JSON on stdin)

`head.md` is a pure function of the plan files (no timestamp), so a no-op run
produces a byte-identical file and never shows up as a spurious diff.

Exit codes: 0 clean · 1 conflicts (manual) · 2 conflicts (--hook, so the agent is
shown stderr).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from plan_parse import (
    HERE,
    ROOT_DISPLAY,
    Conflict,
    Plan,
    LIVE_STATUSES,
    blockers,
    collect,
    display_state,
    force_utf8_stdio,
    format_conflicts,
    item_index,
)

HEAD = HERE / "head.md"

# HEAD is the highest-seq plan in the first non-empty bucket.
HEAD_PREFERENCE = ("in-progress", "draft", "done")


def pick_head(plans: list[Plan]) -> Plan | None:
    for status in HEAD_PREFERENCE:
        bucket = [p for p in plans if p.status == status]
        if bucket:
            return max(bucket, key=lambda p: p.seq)
    return None


def _link(p: Plan) -> str:
    return f"[{p.stem}](./{p.name})"


def _remaining(p: Plan) -> str:
    line = f"待辦待決剩 {p.open_items}/{p.total}"
    if p.handoff_count:
        line += f"，已移交 {p.handoff_count}"
    if p.version < 3:
        line += f"（v{p.version}）"
    return line


def render_open_items(plans: list[Plan]) -> list[str]:
    """One line per open item, across every live v3 plan.

    A per-plan count cannot answer the question you actually arrive with — which plan,
    and which item, owns the thing I was just asked to do. This section answers it
    without opening a single plan file.
    """
    index = item_index(plans)
    live = sorted((p for p in plans if p.status in LIVE_STATUSES), key=lambda p: p.seq, reverse=True)
    rows = [it for p in live if p.version >= 3 for it in p.items if it.is_open]
    legacy = [p for p in live if p.version < 3]

    out = ["", "## 現在開著的（逐格）", ""]
    if rows:
        for it in rows:
            line = f"- `{it.addr}` · **{display_state(it, index)}**"
            if held := blockers(it, index):
                line += "（等 " + "、".join(f"`{a}`" for a in held) + "）"
            out.append(f"{line} — {it.title}")
        out += [
            "",
            f"> 要做某一格：`python3 {ROOT_DISPLAY}/plan-item.py {rows[0].addr}`",
            "> —— 只回那一格的正文與它的依據，不必讀整份計畫。",
        ]
    elif not legacy:
        out.append("（沒有開著的項目）")

    if legacy:
        if rows:
            out.append("")
        seqs = "、".join(p.seq for p in legacy)
        out.append(
            f"> v1 / v2 的計畫（{seqs}）沒有可定址的格子，不在此列 —— 要知道它們欠什麼，"
            "只能開檔。"
        )
    return out


def render_head(plans: list[Plan], conflicts: list[Conflict]) -> str:
    out = [
        "# Plan history — HEAD",
        "",
        f"<!-- Generated by {ROOT_DISPLAY}/update-head.py — do not hand-edit. -->",
        "",
        "## 目前使用中",
        "",
    ]

    head = pick_head(plans)
    if head is None:
        out.append("（尚無任何計畫）")
    else:
        line = f"{_link(head)} — `{head.status}`"
        if head.status == "in-progress":
            line += f"，{_remaining(head)}"
        out.append(line)

    out += render_open_items(plans)
    out += ["", "## draft / in-progress（流水號降序）", ""]

    live = sorted(
        (p for p in plans if p.status in LIVE_STATUSES),
        key=lambda p: p.seq,
        reverse=True,
    )
    if not live:
        out.append("（無）")
    for p in live:
        line = f"- **{p.seq}** {_link(p)} — `{p.status}`"
        if p.status == "in-progress":
            line += f"，{_remaining(p)}"
        out.append(line)

    if conflicts:
        out += [
            "",
            f"> ⚠ 有 {len(conflicts)} 項一致性衝突未解決。",
            f"> 執行 `python3 {ROOT_DISPLAY}/update-head.py` 看明細。",
        ]

    return "\n".join(out) + "\n"


def hook_should_run() -> bool:
    """True when the PostToolUse payload on stdin touched a plan file."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return False
    tool_input = payload.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path") or ""
    if not raw:
        return False
    try:
        path = Path(raw).resolve()
    except OSError:
        return False
    return path.parent == HERE and path.name != "head.md" and path.suffix == ".md"


def main() -> int:
    force_utf8_stdio()
    args = set(sys.argv[1:])
    hook = "--hook" in args
    check_only = "--check" in args

    if hook and not hook_should_run():
        return 0

    report = collect()

    if not check_only:
        rendered = render_head(report.plans, report.errors)
        if not HEAD.exists() or HEAD.read_text(encoding="utf-8") != rendered:
            HEAD.write_text(rendered, encoding="utf-8")
            if not hook:
                print(f"[plan-history] head.md updated ({len(report.plans)} plan(s))")
        elif not hook:
            print(f"[plan-history] head.md already up to date ({len(report.plans)} plan(s))")

    if not report.conflicts:
        return 0

    # Warnings are printed but never fail the run: they ask for a judgement call
    # (split this item, trim this header), and forcing one would just teach the
    # reader to silence them.
    text = format_conflicts(report.conflicts)
    if hook:
        print(text, file=sys.stderr)
        return 2 if report.errors else 0
    print(text)
    return 1 if report.errors else 0


if __name__ == "__main__":
    sys.exit(main())
